import SwiftUI

extension Notification.Name {
    static let appLanguageChanged = Notification.Name("appLanguageChanged")
}

@MainActor
final class LocalizationManager: ObservableObject {
    @Published var currentLanguage: String {
        didSet {
            UserDefaults.standard.set(currentLanguage, forKey: "selectedLanguage")
            NotificationCenter.default.post(name: .appLanguageChanged, object: nil)
        }
    }

    private let supportedLanguages = ["es", "en"]

    private let translations: [String: [String: String]] = [
        "es": [
            "settings.title": "Ajustes",
            "settings.profile": "Perfil",
            "settings.appearance": "Apariencia",
            "settings.fontSize": "Tamano de Fuente",
            "settings.notifications": "Notificaciones",
            "settings.language": "Idioma",
            "settings.privacy": "Privacidad y Seguridad",
            "settings.info": "Informacion",
            "settings.textSize": "Tamano de Texto",
            "settings.currentSize": "Tamano Actual",
            "settings.enableNotifications": "Notificaciones de actualizacion",
            "settings.updateNotificationsDesc": "Recibe un aviso cuando la app tenga una nueva version.",
            "settings.notificationPermissionDenied": "Las notificaciones estan desactivadas en los ajustes del sistema. Activalas para recibir avisos de actualizacion.",
            "settings.theme": "Tema",
            "settings.light": "Modo Claro",
            "settings.dark": "Modo Oscuro",
            "settings.privacyPolicy": "Politica de Privacidad",
            "settings.termsOfService": "Terminos de Servicio",
            "settings.information": "Informacion",
            "settings.about": "Acerca de",
            "settings.support": "Soporte",
            "settings.firebaseTools": "Herramientas Firebase",
            "settings.uploadImages": "Subir Imagenes a Firebase",
            "settings.syncProducts": "Sincronizar Productos",
            "settings.uploadSuccess": "Imagenes subidas y URLs actualizadas en Firestore",
            "settings.uploadError": "Error al subir imagenes",
            "settings.syncSuccess": "Productos sincronizados",
            "settings.syncError": "Error al sincronizar productos",
            "settings.firebaseAlert": "Firebase Imagenes",
            "settings.logout": "Cerrar Sesion",
            "settings.logoutConfirmation": "Estas seguro de que deseas cerrar sesion?",
            "settings.deleteAllProducts": "Borrar TODOS los productos",
            "settings.deleteAllProductsMessage": "Esto elimina TODOS los productos de Firestore de forma permanente. Esta accion no se puede deshacer.",
            "settings.deleteAllProductsButton": "Borrar todo",
            "settings.deleteAllProductsCancel": "Cancelar",
            "settings.deleteAllProductsProgress": "Eliminando productos...",
            "settings.deleteAllProductsSuccess": "Todos los productos fueron eliminados de Firestore.",
            "settings.deleteAllProductsError": "Ocurrio un error al eliminar los productos. Revisa la consola.",
            "settings.liquidGlass": "Liquid Glass",
            "settings.liquidGlassMode": "Modo Liquid Glass",
            "settings.liquidGlassDescription": "Activa superficies de vidrio en toda la aplicacion.",
            "settings.admin": "ADMIN",
            "settings.defaultUser": "Usuario",

            "theme.light": "Modo Claro",
            "theme.dark": "Modo Oscuro",
            "theme.auto": "Automatico",
            "theme.light.desc": "Siempre claro",
            "theme.dark.desc": "Siempre oscuro",
            "theme.auto.desc": "Segun la hora del dia",

            "fontSize.adjust": "Ajusta el tamano del texto",
            "fontSize.apply": "Se aplica en toda la aplicacion",
            "fontSize.reset": "Restablecer",

            "notif.enabled": "Notificaciones Habilitadas",
            "notif.advanced": "Configuracion Avanzada",
            "notif.push": "Notificaciones Push",
            "notif.email": "Correo Electronico",
            "notif.sms": "SMS",

            "lang.spanish": "Espanol",
            "lang.english": "Ingles",
            "lang.es": "Espanol - ES",
            "lang.en": "Ingles - EN",

            "privacy.policy": "Politica de Privacidad",
            "privacy.terms": "Terminos de Servicio",
            "privacy.title": "Politica de Privacidad",
            "privacy.text": "Tus datos estan protegidos con las mas altas medidas de seguridad. No compartimos informacion personal con terceros sin tu consentimiento.",
            "privacy.terms.title": "Terminos de Servicio",
            "privacy.terms.text": "Al usar nuestra aplicacion, aceptas estos terminos. Nos reservamos el derecho de actualizar estos terminos en cualquier momento.",

            "info.version": "Version de la App",
            "info.build": "Numero de Build",
            "info.time": "Hora Actual",
            "info.period": "Periodo del Dia",

            "home.store": "Tienda",
            "home.searchPlaceholder": "Buscar productos",
            "home.categories": "Categorias",
            "home.repairTitle": "Servicio Tecnico Apple",
            "home.repairSubtitle": "Repuestos y reparaciones originales",
            "home.featured": "Destacados",
            "home.newArrivals": "Nuevas Llegadas",
            "home.welcome": "Bienvenido a nuestra tienda",
            "home.noProducts": "No hay productos disponibles",
            "home.noResults": "No se encontraron resultados",
            "home.noCategoryProducts": "No hay productos en esta categoria",

            "category.all": "Todos",
            "category.ipad": "iPad",
            "category.iphone": "iPhone",
            "category.mac": "Mac",
            "category.applewatch": "Apple Watch",
            "category.accessories": "Accesorios",
            "category.products": "productos",
            "category.product": "producto",
            "category.noProducts": "No hay productos en esta categoria",
            "category.todos": "Todos",
            "category.airpods": "AirPods",
            "category.tvhome": "TV y Casa",

            "cart.title": "Carrito",
            "cart.empty": "Tu carrito esta vacio",
            "cart.emptyDescription": "Agrega algunos productos para comenzar",
            "cart.continueShopping": "Continuar comprando",
            "cart.checkout": "Ir al Pago",
            "cart.itemsTotal": "Total de productos",
            "cart.total": "Total",
            "cart.subtotal": "Subtotal",
            "cart.shipping": "Envio",
            "cart.completePurchase": "Completar Compra",
            "cart.sendWhatsApp": "Enviar por WhatsApp",
            "cart.product": "Producto",
            "cart.date": "Fecha",
            "cart.thanks": "Gracias por tu compra!",
            "cart.whatsappMissing": "WhatsApp no esta instalado.",
            "cart.newOrder": "NUEVA COMPRA - TIENDA APPLE",
            "cart.orderDetails": "DETALLES DEL PEDIDO",

            "product.price": "Precio",
            "product.color": "Color",
            "product.capacity": "Capacidad",
            "product.stock": "En Stock",
            "product.outOfStock": "Agotado",
            "product.addToCart": "Agregar al Carrito",
            "product.description": "Descripcion",
            "product.details": "Detalles",
            "product.quantity": "Cantidad",
            "product.youMayAlsoLike": "Tambien te puede interesar",
            "product.recommendedAccessories": "Accesorios recomendados",
            "cart.youMayAlsoLike": "Tambien te puede interesar",
            "product.reviews": "reseñas",
            "product.availableColors": "Colores disponibles",
            "product.recommendedForYou": "Recomendado para ti",
            "product.uniqueOption": "Unico",

            "support.title": "Soporte",
            "support.chat": "Chat",
            "support.hello": "Hola de nuevo!",
            "support.howCanHelp": "Que cosas puedes hacer?",
            "support.typeSomething": "Escribe algo...",
            "support.send": "Enviar",
            "support.heading": "Como podemos ayudarte?",
            "support.subheading": "Elige una categoria o describe tu problema",
            "support.placeholder": "Escribe tu pregunta...",
            "support.typing": "Escribiendo...",
            "support.available": "Disponible",
            "support.hideKeyboard": "Ocultar teclado",
            "support.clearChat": "Limpiar chat",
            "support.clearMessage": "Estas seguro de que deseas eliminar todo el historial?",
            "support.cancel": "Cancelar",
            "support.clear": "Limpiar",
            "support.issuePrefix": "Tengo un problema con:",
            "support.category1.title": "Pantallas y reparaciones",
            "support.category1.subtitle": "Roturas, fallas tactiles, cambio de pantalla",
            "support.category2.title": "Conectividad",
            "support.category2.subtitle": "WiFi, Bluetooth, senal y redes",
            "support.category3.title": "Bateria y carga",
            "support.category3.subtitle": "Duracion, carga lenta, puerto danado",
            "support.category4.title": "Almacenamiento y software",
            "support.category4.subtitle": "Espacio, actualizaciones, rendimiento",
            "support.hours": "Lun - Vie: 9:00 - 18:00",
            "support.avgResponseTime": "Tiempo promedio",
            "support.helpSection": "COMO PODEMOS AYUDARTE",
            "support.hubSubtitle": "Elige si quieres conversar con el chatbot tecnico o abrir recomendaciones rapidas de compra.",
            "support.chatSubtitle": "Habla con el asistente tecnico para resolver dudas de reparaciones y repuestos.",
            "support.recommendations": "Recomendaciones",
            "support.recommendationsSubtitle": "Explora sugerencias de productos segun lo que necesitas comprar.",
            "support.exploreByCategory": "EXPLORA POR CATEGORIA",
            "support.quickRecommendations": "Recomendaciones rapidas",
            "support.quickRecommendationsSubtitle": "Entrar aqui te lleva a categorias utiles para elegir el producto correcto segun el uso que le daras.",
            "support.study": "Para estudiar",
            "support.studySubtitle": "iPad y accesorios que rinden bien en clases y tareas.",
            "support.work": "Para trabajo",
            "support.workSubtitle": "Mac y accesorios para productividad diaria.",
            "support.dailyUse": "Para uso diario",
            "support.dailyUseSubtitle": "iPhone con buena relacion precio-rendimiento.",
            "support.audioMobility": "Audio y movilidad",
            "support.audioMobilitySubtitle": "AirPods y opciones portatiles para el dia a dia.",
            "support.fullCatalog": "Ver catalogo completo",
            "support.fullCatalogSubtitle": "Explora todas las categorias disponibles de la tienda.",

            "orders.title": "Mis Ordenes",
            "orders.empty.title": "Aun no tienes compras",
            "orders.empty.subtitle": "Cuando realices una compra, aparecera aqui",
            "orders.noOrders": "Aun no tienes compras",
            "orders.noOrdersDesc": "Cuando realices una compra, aparecera aqui",
            "orders.delivered": "Entregada",
            "orders.shipped": "En camino",
            "orders.processing": "Procesando",
            "orders.cancelled": "Cancelada",
            "orders.total": "Total",
            "orders.date": "Fecha",
            "orders.status": "Estado",
            "orders.items": "Articulos",

            "common.home": "Inicio",
            "common.assistant": "Asistente",
            "common.about": "Sobre Nosotros",
            "common.profile": "Perfil",
            "orders": "Mis Compras",
            "cancel": "Cancelar",
            "Pre save": "Guardar",
            "delete": "Eliminar",
            "edit": "Editar",
            "loading": "Cargando...",
            "error": "Error",
            "success": "Exito",
            "home": "Inicio",
            "ishop": "Tienda",
            "assistant": "Asistente",
            "About us": "Sobre Nosotros",
            "profile": "Perfil",
            "retry": "Reintentar",
            "common.shop": "Tienda",

            "profile.selectPhoto": "Seleccionar Foto",
            "profile.name": "Nombre",
            "profile.lastName": "Apellido",
            "profile.email": "Correo Electronico",
            "profile.address": "Direccion",
            "profile.age": "Edad",
            "profile.birthDate": "Fecha de Nacimiento",
            "profile.phone": "Telefono",
            "profile.save": "Guardar Cambios",
            "profile.edit": "Editar Perfil",
            "profile.title": "Mi Perfil",
            "profile.editPhoto": "Editar foto",
            "profile.saveChanges": "Guardar cambios",
            "profile.signOut": "Cerrar sesion",
            "profile.signOutConfirm": "Estas seguro que quieres cerrar sesion?",
            "profile.signOutTitle": "Cerrar sesion",
            "profile.cancel": "Cancelar",
            "profile.emailPlaceholder": "Correo",
            "profile.phonePlaceholder": "Telefono",
            "profile.firstNamePlaceholder": "Nombre",
            "profile.lastNamePlaceholder": "Apellido",

            "login.termsAndConditions": "Aceptar terminos y condiciones",
            "login.signIn": "Iniciar Sesion",
            "login.continueAsGuest": "Continuar como Invitado",
            "login.termsPlaceholder": "Lorem ipsum dolor sit amet...",
            "login.close": "Cerrar",
            "login.guest": "Invitado",

            "chat.title": "Gemini AI",
            "chat.typing": "escribiendo...",
            "chat.online": "en linea",
            "chat.clearChat": "Limpiar Chat",
            "chat.clearConfirm": "Para confirmar, deseas eliminar todo el historial de conversacion?",
            "chat.emptyTitle": "En que te ayudo?",
            "chat.emptySubtitle": "Preguntame sobre productos, precios, repuestos y reparaciones, o cualquier duda que tengas",
            "chat.suggestion1": "Hola, que puedo hacer en esta app?",
            "chat.suggestion2": "Que iPhone me recomiendas?",
            "chat.suggestion3": "Tienen repuestos y servicio tecnico?",
            "chat.suggestion4": "Cuentame algo interesante",
            "chat.messagePlaceholder": "Mensaje",

            "repair.title": "Servicio Tecnico Apple",
            "repair.header": "Repuestos y Reparaciones",
            "repair.subtitle": "Repuestos originales con garantia e instalacion profesional.",
            "repair.category": "Categoria",
            "repair.model": "Modelo",
            "repair.noParts": "Sin repuestos disponibles para este modelo.",
            "repair.price": "Precio de reparacion",
            "repair.estimatedTime": "Tiempo estimado",
            "repair.warranty": "Garantia",
            "repair.warrantyValue": "90 dias en mano de obra",
            "repair.part": "Repuesto",
            "repair.original": "Original Apple",
            "repair.compatibleWith": "Compatible con",
            "repair.request": "Solicitar reparacion",
            "repair.whatsappPrefix": "Hola, me interesa el servicio de reparacion",
            "repair.warrantyIncluded": "Garantia incluida",

            "product.noImage": "Sin imagen",
            "product.freeShipping": "Envio gratis",
            "product.returnDays": "30 dias devolucion",
            "product.officialWarranty": "Garantia oficial",
            "product.addedToCart": "Agregado al carrito",

            "payment.summary": "Resumen del pedido",
            "payment.chooseMethod": "Elige como pagar",
            "payment.yape": "Pagar con Yape",
            "payment.yapeSubtitle": "Rapido y sin comision",
            "payment.interbank": "Transferencia Interbank",
            "payment.interbankSubtitle": "Cuenta o CCI",
            "payment.card": "Tarjeta de credito/debito",
            "payment.cardSubtitle": "Visa, Mastercard - via Culqi",
            "payment.checkout": "Checkout",
            "payment.yapeAmount": "Yapea",
            "payment.holder": "Titular",
            "payment.yapeNumber": "Numero Yape",
            "payment.exactAmount": "Monto exacto",
            "payment.yapeHint": "Luego de yapear, envia el comprobante por WhatsApp al mismo numero.",
            "payment.confirmed": "Ya yapie ✓",
            "payment.transferAmount": "Transfiere",
            "payment.interbankHint": "Envia el voucher por WhatsApp para confirmar tu pedido.",
            "payment.transferred": "Ya transferi ✓",
            "payment.accountNumber": "N° de cuenta",
            "payment.cci": "CCI",
            "payment.cardTitle": "Tarjeta de pago",
            "payment.cardSubtitleText": "Ingresa los datos de tu tarjeta",
            "payment.cardNumber": "Numero de tarjeta",
            "payment.cardName": "Nombre en la tarjeta",
            "payment.expiry": "MM/AA",
            "payment.cvv": "CVV",
            "payment.secure": "Pago seguro - Procesado por Culqi",
            "payment.payAmount": "Pagar S/",
            "payment.successTitle": "Pago registrado!",
            "payment.successMessage": "Tu pedido fue guardado.\nTe contactaremos para confirmar.",
            "payment.backHome": "Volver al inicio",

            "about.title": "Sobre Nosotros",
            "about.subtitle": "Nuestra historia & valores",
            "about.heroTitle": "Innovacion & Excelencia",
            "about.heroSubtitle": "Transformando el futuro con tecnologia de punta",
            "about.startTitle": "Nuestro Comienzo",
            "about.years": "Anios",
            "about.users": "Usuarios",
            "about.satisfaction": "Satisfaccion",
            "about.mission": "Mision",
            "about.missionDesc": "Proporcionar herramientas innovadoras que permitan a nuestros clientes alcanzar sus objetivos",
            "about.vision": "Vision",
            "about.visionDesc": "Ser lideres reconocidos por excelencia, innovacion y dedicacion en la industria",
            "about.values": "Nuestros Valores",
            "about.passion": "Pasion",
            "about.innovation": "Innovacion",
            "about.collaboration": "Colaboracion",
            "about.integrity": "Integridad",
            "about.timeline": "Nuestro Recorrido",
            "about.timeline2019": "Inicio del proyecto",
            "about.timeline2021": "Primer lanzamiento oficial",
            "about.timeline2023": "Alcanzamos 10K usuarios",
            "about.timeline2024": "Expansion regional",
            "about.hours": "Lunes a Viernes: 9:00 - 18:00",
            "about.available": "Estamos disponibles para ayudarte",
            "about.contactSupport": "Preguntas o sugerencias? Contactanos desde la seccion de Soporte",
            "about.storyPart1": "Hace mas de 5 anios, nuestro equipo decidio crear una solucion innovadora para transformar la forma en que los clientes interactuan con las marcas.",
            "about.storyPart2": "Lo que comenzo como una pequenia idea, se ha convertido en una plataforma confiable que sirve a miles de usuarios.",

            "common.back": "Atras",
            "common.copy": "Copiar",
            "common.copied": "Copiado!",
            "payment.transferPrefix": "Transfiere",
            "payment.transferSuffix": "a esta cuenta",

            "cart.collapse": "Ver menos",
            "cart.expand": "Ver más detalles",
            "common.loading": "Cargando...",
            "common.welcomeBack": "¡Bienvenido de nuevo",
            "product.searchPlaceholder": "Buscar productos...",
            "product.youSave": "Ahorras %@%",
            "payment.methodCard": "Tarjeta",
            "payment.whatsappHeader": "🛒 *COMPRA - TIENDA APPLE*",
            "profile.userFallback": "Usuario",
            "profile.guestName": "Invitado",
            "theme.name.light": "Claro",
            "theme.name.dark": "Oscuro",
            "theme.name.auto": "Automático",

            "support.voicePermissionDenied": "Activa el permiso de micrófono y reconocimiento de voz en Ajustes para usar el modo voz.",
            "support.voiceListening": "Te escucho… habla con confianza 🎙️",
            "support.voiceResponding": "Respondiendo en voz alta…",
            "support.voiceIdle": "Toca el micrófono y haz tu pregunta. La conversación continúa igual que en el chat.",
            "support.offTopic": "¡Hola! 👋 Puedo ayudarte con productos en stock (iPhone, iPad, Mac, Apple Watch, AirPods y accesorios), repuestos y servicio técnico Apple. ¿Sobre qué quieres consultar?",
            "support.whatsappMessage": "¡Hola! 👋 Me gustaría obtener más información sobre sus productos.",

            "about.value.passion.desc": "Nos apasiona lo que hacemos. Cada proyecto, cada interacción y cada decisión es tomada con dedicación y entusiasmo. Creemos que la pasión es el combustible que impulsa la innovación y la excelencia en todo lo que hacemos. Esa energía se refleja en el cuidado con el que atendemos cada reparación, cada recomendación de producto y cada conversación con nuestros clientes.",
            "about.value.innovation.desc": "Buscamos constantemente nuevas formas de mejorar y evolucionar. La innovación no es solo una palabra para nosotros, es parte de nuestro ADN. Nos desafiamos a nosotros mismos a pensar diferente, adoptar nuevas tecnologías y encontrar soluciones creativas que hagan tu experiencia más simple, rápida y confiable.",
            "about.value.collaboration.desc": "Creemos en el poder del trabajo en equipo. La colaboración nos permite combinar diferentes perspectivas y talentos para crear algo extraordinario. Trabajamos codo a codo, tanto internamente como con nuestros clientes, porque sabemos que las mejores soluciones surgen cuando escuchamos y sumamos esfuerzos. Juntos somos más fuertes.",
            "about.value.integrity.desc": "Actuamos siempre con honestidad, transparencia y responsabilidad. La integridad es la base de todas nuestras relaciones y decisiones: precios claros, diagnósticos honestos y compromisos que cumplimos. Hacemos lo correcto, incluso cuando nadie está mirando, porque tu confianza es lo más valioso que construimos.",

            "legal.updated": "Actualizado: %@",
            "legal.privacy.title": "Política de Privacidad",
            "legal.privacy.subtitle": "Aquí explicamos cómo tratamos tus datos dentro de la app y cuándo usas nuestros servicios.",
            "legal.privacy.date": "31 de julio de 2026",
            "legal.privacy.s1.title": "Datos que recopilamos",
            "legal.privacy.s1.body": "Podemos guardar datos de cuenta, historial de compras, mensajes de soporte y preferencias de la app para hacer que tu experiencia sea más rápida y personalizada.",
            "legal.privacy.s2.title": "Uso de la información",
            "legal.privacy.s2.body": "Usamos la información para gestionar tu cuenta, dar soporte, procesar pedidos y mejorar recomendaciones dentro de la aplicación.",
            "legal.privacy.s3.title": "Protección y seguridad",
            "legal.privacy.s3.body": "Aplicamos medidas técnicas y organizativas para proteger tus datos. No compartimos información personal con terceros salvo que sea necesario para prestar el servicio o que tú lo autorices.",
            "legal.privacy.s4.title": "Contacto",
            "legal.privacy.s4.body": "Si quieres revisar, corregir o eliminar información asociada a tu cuenta, puedes escribir a soporte@tech.com o usar la sección de soporte.",
            "legal.terms.title": "Términos de Servicio",
            "legal.terms.subtitle": "Estas reglas explican cómo usar la app, comprar productos y solicitar soporte.",
            "legal.terms.date": "31 de julio de 2026",
            "legal.terms.s1.title": "Aceptación",
            "legal.terms.s1.body": "Al usar la app aceptas estos términos y confirmas que la información que registras es veraz y que utilizarás la plataforma de forma responsable.",
            "legal.terms.s2.title": "Compras y pagos",
            "legal.terms.s2.body": "Los precios, stock y disponibilidad pueden cambiar según el inventario. Antes de pagar, revisa bien el producto, la configuración elegida y el total final del pedido.",
            "legal.terms.s3.title": "Soporte y servicio",
            "legal.terms.s3.body": "La sección de soporte te permite abrir el chatbot técnico o ver recomendaciones de productos. El asesoramiento dentro de la app es orientativo y no reemplaza una evaluación técnica presencial cuando hace falta.",
            "legal.terms.s4.title": "Cambios",
            "legal.terms.s4.body": "Podemos actualizar estos términos en cualquier momento para reflejar cambios en el servicio, catálogo o políticas internas. Te recomendamos revisarlos periódicamente."
        ],
        "en": [
            "settings.title": "Settings",
            "settings.profile": "Profile",
            "settings.appearance": "Appearance",
            "settings.fontSize": "Font Size",
            "settings.notifications": "Notifications",
            "settings.language": "Language",
            "settings.privacy": "Privacy & Security",
            "settings.info": "Information",
            "settings.textSize": "Text Size",
            "settings.currentSize": "Current Size",
            "settings.enableNotifications": "Update notifications",
            "settings.updateNotificationsDesc": "Get an alert when the app gets a new version.",
            "settings.notificationPermissionDenied": "Notifications are disabled in system settings. Enable them to receive update alerts.",
            "settings.theme": "Theme",
            "settings.light": "Light Mode",
            "settings.dark": "Dark Mode",
            "settings.privacyPolicy": "Privacy Policy",
            "settings.termsOfService": "Terms of Service",
            "settings.information": "Information",
            "settings.about": "About",
            "settings.support": "Support",
            "settings.firebaseTools": "Firebase Tools",
            "settings.uploadImages": "Upload Images to Firebase",
            "settings.syncProducts": "Sync Products",
            "settings.uploadSuccess": "Images uploaded and URLs updated in Firestore",
            "settings.uploadError": "Error uploading images",
            "settings.syncSuccess": "Products synced",
            "settings.syncError": "Error syncing products",
            "settings.firebaseAlert": "Firebase Images",
            "settings.logout": "Sign Out",
            "settings.logoutConfirmation": "Are you sure you want to sign out?",
            "settings.deleteAllProducts": "Delete ALL Products",
            "settings.deleteAllProductsMessage": "This permanently deletes EVERY product from Firestore. This action cannot be undone.",
            "settings.deleteAllProductsButton": "Delete all",
            "settings.deleteAllProductsCancel": "Cancel",
            "settings.deleteAllProductsProgress": "Deleting products...",
            "settings.deleteAllProductsSuccess": "All products were deleted from Firestore.",
            "settings.deleteAllProductsError": "An error occurred while deleting products. Check the console.",
            "settings.liquidGlass": "Liquid Glass",
            "settings.liquidGlassMode": "Liquid Glass Mode",
            "settings.liquidGlassDescription": "Enables glass surfaces throughout the app.",
            "settings.admin": "ADMIN",
            "settings.defaultUser": "User",

            "theme.light": "Light Mode",
            "theme.dark": "Dark Mode",
            "theme.auto": "Automatic",
            "theme.light.desc": "Always light",
            "theme.dark.desc": "Always dark",
            "theme.auto.desc": "Based on the time of day",

            "fontSize.adjust": "Adjust the text size",
            "fontSize.apply": "Applies throughout the app",
            "fontSize.reset": "Reset",

            "notif.enabled": "Notifications Enabled",
            "notif.advanced": "Advanced Settings",
            "notif.push": "Push Notifications",
            "notif.email": "Email",
            "notif.sms": "SMS",

            "lang.spanish": "Spanish",
            "lang.english": "English",
            "lang.es": "Spanish - ES",
            "lang.en": "English - EN",

            "privacy.policy": "Privacy Policy",
            "privacy.terms": "Terms of Service",
            "privacy.title": "Privacy Policy",
            "privacy.text": "Your data is protected with the highest security measures. We do not share personal information with third parties without your consent.",
            "privacy.terms.title": "Terms of Service",
            "privacy.terms.text": "By using our app, you agree to these terms. We reserve the right to update them at any time.",

            "info.version": "App Version",
            "info.build": "Build Number",
            "info.time": "Current Time",
            "info.period": "Time Period",

            "home.store": "Store",
            "home.searchPlaceholder": "Search products",
            "home.categories": "Categories",
            "home.repairTitle": "Apple Service Center",
            "home.repairSubtitle": "Original parts and repairs",
            "home.featured": "Featured",
            "home.newArrivals": "New Arrivals",
            "home.welcome": "Welcome to our store",
            "home.noProducts": "No products available",
            "home.noResults": "No results found",
            "home.noCategoryProducts": "No products in this category",

            "category.all": "All",
            "category.ipad": "iPad",
            "category.iphone": "iPhone",
            "category.mac": "Mac",
            "category.applewatch": "Apple Watch",
            "category.accessories": "Accessories",
            "category.products": "products",
            "category.product": "product",
            "category.noProducts": "No products in this category",
            "category.todos": "All",
            "category.airpods": "AirPods",
            "category.tvhome": "TV & Home",

            "cart.title": "Cart",
            "cart.empty": "Your cart is empty",
            "cart.emptyDescription": "Add some products to get started",
            "cart.continueShopping": "Continue shopping",
            "cart.checkout": "Go to Checkout",
            "cart.itemsTotal": "Items total",
            "cart.total": "Total",
            "cart.subtotal": "Subtotal",
            "cart.shipping": "Shipping",
            "cart.completePurchase": "Complete Purchase",
            "cart.sendWhatsApp": "Send via WhatsApp",
            "cart.product": "Product",
            "cart.date": "Date",
            "cart.thanks": "Thanks for your purchase!",
            "cart.whatsappMissing": "WhatsApp is not installed.",
            "cart.newOrder": "NEW ORDER - APPLE STORE",
            "cart.orderDetails": "ORDER DETAILS",

            "product.price": "Price",
            "product.color": "Color",
            "product.capacity": "Capacity",
            "product.stock": "In Stock",
            "product.outOfStock": "Out of Stock",
            "product.addToCart": "Add to Cart",
            "product.description": "Description",
            "product.details": "Details",
            "product.quantity": "Quantity",
            "product.youMayAlsoLike": "You may also like",
            "product.recommendedAccessories": "Recommended accessories",
            "cart.youMayAlsoLike": "You may also like",
            "product.reviews": "reviews",
            "product.availableColors": "Available colors",
            "product.recommendedForYou": "Recommended for you",
            "product.uniqueOption": "Single option",

            "support.title": "Support",
            "support.chat": "Chat",
            "support.hello": "Hello again!",
            "support.howCanHelp": "What can you do?",
            "support.typeSomething": "Type something...",
            "support.send": "Send",
            "support.heading": "How can we help you?",
            "support.subheading": "Choose a category or describe your issue",
            "support.placeholder": "Type your question...",
            "support.typing": "Typing...",
            "support.available": "Available",
            "support.hideKeyboard": "Hide keyboard",
            "support.clearChat": "Clear chat",
            "support.clearMessage": "Are you sure you want to delete all history?",
            "support.cancel": "Cancel",
            "support.clear": "Clear",
            "support.issuePrefix": "I have a problem with:",
            "support.category1.title": "Screen and repairs",
            "support.category1.subtitle": "Cracks, touch issues, screen replacement",
            "support.category2.title": "Connectivity",
            "support.category2.subtitle": "WiFi, Bluetooth, signal and networks",
            "support.category3.title": "Battery and charging",
            "support.category3.subtitle": "Battery life, slow charging, damaged port",
            "support.category4.title": "Storage and software",
            "support.category4.subtitle": "Space, updates, performance",
            "support.hours": "Mon - Fri: 9:00 - 18:00",
            "support.avgResponseTime": "Average response time",
            "support.helpSection": "HOW CAN WE HELP YOU",
            "support.hubSubtitle": "Choose whether to chat with the technical assistant or open quick shopping recommendations.",
            "support.chatSubtitle": "Talk to the technical assistant to resolve questions about repairs and parts.",
            "support.recommendations": "Recommendations",
            "support.recommendationsSubtitle": "Explore product suggestions based on what you need to buy.",
            "support.exploreByCategory": "EXPLORE BY CATEGORY",
            "support.quickRecommendations": "Quick recommendations",
            "support.quickRecommendationsSubtitle": "This area takes you to useful categories to choose the right product for how you will use it.",
            "support.study": "For studying",
            "support.studySubtitle": "iPad and accessories that work well for classes and assignments.",
            "support.work": "For work",
            "support.workSubtitle": "Mac and accessories for daily productivity.",
            "support.dailyUse": "For everyday use",
            "support.dailyUseSubtitle": "iPhones with good value for the price.",
            "support.audioMobility": "Audio and mobility",
            "support.audioMobilitySubtitle": "AirPods and portable options for everyday life.",
            "support.fullCatalog": "View full catalog",
            "support.fullCatalogSubtitle": "Explore all available store categories.",

            "orders.title": "My Orders",
            "orders.empty.title": "You do not have any purchases yet",
            "orders.empty.subtitle": "When you make a purchase, it will appear here",
            "orders.noOrders": "You do not have any purchases yet",
            "orders.noOrdersDesc": "When you make a purchase, it will appear here",
            "orders.delivered": "Delivered",
            "orders.shipped": "Shipped",
            "orders.processing": "Processing",
            "orders.cancelled": "Cancelled",
            "orders.total": "Total",
            "orders.date": "Date",
            "orders.status": "Status",
            "orders.items": "Items",

            "common.home": "Home",
            "common.assistant": "Assistant",
            "common.about": "About Us",
            "common.profile": "Profile",
            "orders": "My Purchases",
            "cancel": "Cancel",
            "Pre save": "Save",
            "delete": "Delete",
            "edit": "Edit",
            "loading": "Loading...",
            "error": "Error",
            "success": "Success",
            "home": "Home",
            "ishop": "Store",
            "assistant": "Assistant",
            "About us": "About Us",
            "profile": "Profile",
            "retry": "Retry",
            "common.shop": "Store",

            "profile.selectPhoto": "Select Photo",
            "profile.name": "Name",
            "profile.lastName": "Last Name",
            "profile.email": "Email",
            "profile.address": "Address",
            "profile.age": "Age",
            "profile.birthDate": "Date of Birth",
            "profile.phone": "Phone",
            "profile.save": "Save Changes",
            "profile.edit": "Edit Profile",
            "profile.title": "My Profile",
            "profile.editPhoto": "Edit photo",
            "profile.saveChanges": "Save changes",
            "profile.signOut": "Sign out",
            "profile.signOutConfirm": "Are you sure you want to sign out?",
            "profile.signOutTitle": "Sign out",
            "profile.cancel": "Cancel",
            "profile.emailPlaceholder": "Email",
            "profile.phonePlaceholder": "Phone",
            "profile.firstNamePlaceholder": "First name",
            "profile.lastNamePlaceholder": "Last name",

            "login.termsAndConditions": "Accept terms and conditions",
            "login.signIn": "Sign In",
            "login.continueAsGuest": "Continue as Guest",
            "login.termsPlaceholder": "Lorem ipsum dolor sit amet...",
            "login.close": "Close",
            "login.guest": "Guest",

            "chat.title": "Gemini AI",
            "chat.typing": "typing...",
            "chat.online": "online",
            "chat.clearChat": "Clear Chat",
            "chat.clearConfirm": "To confirm, do you want to delete all conversation history?",
            "chat.emptyTitle": "How can I help you?",
            "chat.emptySubtitle": "Ask me about products, prices, parts and repairs, or any question you have",
            "chat.suggestion1": "Hi, what can I do in this app?",
            "chat.suggestion2": "Which iPhone do you recommend?",
            "chat.suggestion3": "Do you have parts and service?",
            "chat.suggestion4": "Tell me something interesting",
            "chat.messagePlaceholder": "Message",

            "repair.title": "Apple Service Center",
            "repair.header": "Parts and Repairs",
            "repair.subtitle": "Original parts with warranty and professional installation.",
            "repair.category": "Category",
            "repair.model": "Model",
            "repair.noParts": "No parts available for this model.",
            "repair.price": "Repair price",
            "repair.estimatedTime": "Estimated time",
            "repair.warranty": "Warranty",
            "repair.warrantyValue": "90 days labor warranty",
            "repair.part": "Part",
            "repair.original": "Original Apple",
            "repair.compatibleWith": "Compatible with",
            "repair.request": "Request repair",
            "repair.whatsappPrefix": "Hi, I am interested in the repair service",
            "repair.warrantyIncluded": "Warranty included",

            "product.noImage": "No image",
            "product.freeShipping": "Free shipping",
            "product.returnDays": "30-day returns",
            "product.officialWarranty": "Official warranty",
            "product.addedToCart": "Added to cart",

            "payment.summary": "Order summary",
            "payment.chooseMethod": "Choose how to pay",
            "payment.yape": "Pay with Yape",
            "payment.yapeSubtitle": "Fast and no fee",
            "payment.interbank": "Interbank transfer",
            "payment.interbankSubtitle": "Account or CCI",
            "payment.card": "Credit/debit card",
            "payment.cardSubtitle": "Visa, Mastercard - via Culqi",
            "payment.checkout": "Checkout",
            "payment.yapeAmount": "Yape",
            "payment.holder": "Account holder",
            "payment.yapeNumber": "Yape number",
            "payment.exactAmount": "Exact amount",
            "payment.yapeHint": "After paying with Yape, send the receipt by WhatsApp to the same number.",
            "payment.confirmed": "Paid ✓",
            "payment.transferAmount": "Transfer",
            "payment.interbankHint": "Send the voucher by WhatsApp to confirm your order.",
            "payment.transferred": "Transferred ✓",
            "payment.accountNumber": "Account number",
            "payment.cci": "CCI",
            "payment.cardTitle": "Payment card",
            "payment.cardSubtitleText": "Enter your card details",
            "payment.cardNumber": "Card number",
            "payment.cardName": "Name on card",
            "payment.expiry": "MM/YY",
            "payment.cvv": "CVV",
            "payment.secure": "Secure payment - Processed by Culqi",
            "payment.payAmount": "Pay S/",
            "payment.successTitle": "Payment recorded!",
            "payment.successMessage": "Your order was saved.\nWe will contact you to confirm.",
            "payment.backHome": "Back to home",

            "about.title": "About Us",
            "about.subtitle": "Our story & values",
            "about.heroTitle": "Innovation & Excellence",
            "about.heroSubtitle": "Transforming the future with cutting-edge technology",
            "about.startTitle": "Our Beginning",
            "about.years": "Years",
            "about.users": "Users",
            "about.satisfaction": "Satisfaction",
            "about.mission": "Mission",
            "about.missionDesc": "Provide innovative tools that help our customers reach their goals",
            "about.vision": "Vision",
            "about.visionDesc": "Be recognized leaders for excellence, innovation and dedication in the industry",
            "about.values": "Our Values",
            "about.passion": "Passion",
            "about.innovation": "Innovation",
            "about.collaboration": "Collaboration",
            "about.integrity": "Integrity",
            "about.timeline": "Our Journey",
            "about.timeline2019": "Project start",
            "about.timeline2021": "First official launch",
            "about.timeline2023": "Reached 10K users",
            "about.timeline2024": "Regional expansion",
            "about.hours": "Monday to Friday: 9:00 - 18:00",
            "about.available": "We are available to help you",
            "about.contactSupport": "Questions or suggestions? Contact us from the Support section",
            "about.storyPart1": "More than 5 years ago, our team decided to create an innovative solution to transform the way customers interact with brands.",
            "about.storyPart2": "What started as a small idea has become a trusted platform that serves thousands of users.",

            "common.back": "Back",
            "common.copy": "Copy",
            "common.copied": "Copied!",
            "payment.transferPrefix": "Transfer",
            "payment.transferSuffix": "to this account",

            "cart.collapse": "Show less",
            "cart.expand": "View more details",
            "common.loading": "Loading...",
            "common.welcomeBack": "Welcome back",
            "product.searchPlaceholder": "Search products...",
            "product.youSave": "You save %@%",
            "payment.methodCard": "Card",
            "payment.whatsappHeader": "🛒 *ORDER - APPLE STORE*",
            "profile.userFallback": "User",
            "profile.guestName": "Guest",
            "theme.name.light": "Light",
            "theme.name.dark": "Dark",
            "theme.name.auto": "Automatic",

            "support.voicePermissionDenied": "Enable microphone and speech recognition permission in Settings to use voice mode.",
            "support.voiceListening": "I'm listening… speak confidently 🎙️",
            "support.voiceResponding": "Responding out loud…",
            "support.voiceIdle": "Tap the microphone and ask your question. The conversation continues just like in the chat.",
            "support.offTopic": "Hi! 👋 I can help you with products in stock (iPhone, iPad, Mac, Apple Watch, AirPods and accessories), spare parts and Apple technical service. What would you like to ask about?",
            "support.whatsappMessage": "Hi! 👋 I would like more information about your products.",

            "about.value.passion.desc": "We are passionate about what we do. Every project, every interaction and every decision is made with dedication and enthusiasm. We believe passion is the fuel that drives innovation and excellence in everything we do. That energy shows in the care we put into every repair, every product recommendation and every conversation with our customers.",
            "about.value.innovation.desc": "We constantly look for new ways to improve and evolve. Innovation is not just a word for us, it is part of our DNA. We challenge ourselves to think differently, adopt new technologies and find creative solutions that make your experience simpler, faster and more reliable.",
            "about.value.collaboration.desc": "We believe in the power of teamwork. Collaboration lets us combine different perspectives and talents to create something extraordinary. We work side by side, both internally and with our customers, because we know the best solutions emerge when we listen and join efforts. Together we are stronger.",
            "about.value.integrity.desc": "We always act with honesty, transparency and responsibility. Integrity is the foundation of all our relationships and decisions: clear prices, honest diagnostics and commitments we keep. We do the right thing, even when no one is watching, because your trust is the most valuable thing we build.",

            "legal.updated": "Updated: %@",
            "legal.privacy.title": "Privacy Policy",
            "legal.privacy.subtitle": "Here we explain how we handle your data inside the app and when you use our services.",
            "legal.privacy.date": "July 31, 2026",
            "legal.privacy.s1.title": "Data we collect",
            "legal.privacy.s1.body": "We may store account data, purchase history, support messages and app preferences to make your experience faster and more personalized.",
            "legal.privacy.s2.title": "Use of information",
            "legal.privacy.s2.body": "We use the information to manage your account, provide support, process orders and improve recommendations within the app.",
            "legal.privacy.s3.title": "Protection and security",
            "legal.privacy.s3.body": "We apply technical and organizational measures to protect your data. We do not share personal information with third parties unless necessary to provide the service or you authorize it.",
            "legal.privacy.s4.title": "Contact",
            "legal.privacy.s4.body": "If you want to review, correct or delete information associated with your account, you can write to soporte@tech.com or use the support section.",
            "legal.terms.title": "Terms of Service",
            "legal.terms.subtitle": "These rules explain how to use the app, buy products and request support.",
            "legal.terms.date": "July 31, 2026",
            "legal.terms.s1.title": "Acceptance",
            "legal.terms.s1.body": "By using the app you accept these terms and confirm that the information you register is truthful and that you will use the platform responsibly.",
            "legal.terms.s2.title": "Purchases and payments",
            "legal.terms.s2.body": "Prices, stock and availability may change according to inventory. Before paying, carefully review the product, the chosen configuration and the final order total.",
            "legal.terms.s3.title": "Support and service",
            "legal.terms.s3.body": "The support section lets you open the technical chatbot or view product recommendations. In-app advice is guidance only and does not replace an in-person technical evaluation when needed.",
            "legal.terms.s4.title": "Changes",
            "legal.terms.s4.body": "We may update these terms at any time to reflect changes in the service, catalog or internal policies. We recommend reviewing them periodically."
        ]
    ]

    init() {
        let savedLanguage = UserDefaults.standard.string(forKey: "selectedLanguage")
        if let savedLanguage, supportedLanguages.contains(savedLanguage) {
            currentLanguage = savedLanguage
        } else {
            currentLanguage = Locale.preferredLanguages.first?.hasPrefix("en") == true ? "en" : "es"
        }
    }

    func setLanguage(_ language: String) {
        currentLanguage = supportedLanguages.contains(language) ? language : "es"
    }

    func translate(_ key: String) -> String {
        translations[currentLanguage]?[key]
        ?? translations["es"]?[key]
        ?? key
    }
}


